service : login
securityGroupIds: sg-802f59f1
subnetIds: subnet-edadc9e1
providerRuntime : nodejs4.3
providerMemorySize : 256
providerTimeout : 160
region: us-east-1
domain : platform
# Put your custom role here which has the IAM permissions required by your code
iamRoleARN: arn:aws:iam::682452625784:role/lambda1_basic_execution_1

owner: dbabu
require_internal_access: true
